[workspace]
resolver = "2"
members = [
    "kotlin-lexer",
    "kotlin-ast",
    "kotlin-hir",
    "kotlin-parse",
    "kotlin-span",
    "kotlin-error",
    "krab-codegen", 
    "krab-tir",
    "krab-lowering"
]

[profile.release]
codegen-units = 1
lto = true
strip = true
rpath = true