[workspace]
resolver = "2"
members = [
    "kotlin-lexer",
    "kotlin-ast",
    "kotlin-hir",
    "kotlin-parse",
    "kotlin-span",
    #"kotlin-llvm",
    "kotlin-error",
    "krab-codegen", 
    "krab-tir"
, "krab-lowering"]
