[package]
name = "kotlin-span"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "2.2.6"
scoped-tls = "1.0.1"
rustc-hash = "1.1.0"